/**
 * AICore Stub Loader
 *
 * Parses AICore agent/skill stub files (schema: aicore-mcp-stub/v2).
 * Provides discovery, filtering, and schema retrieval for MCP tools.
 *
 * Stubs are lightweight interface declarations that map to MCP tool calls.
 * They do NOT contain full agent/skill prompts (those are in AICore/).
 */
import { readFileSync, existsSync, readdirSync } from 'fs';
import { join, extname } from 'path';
import { parse as parseYaml } from 'yaml';
import { AICORE_AGENTS_DIR, AICORE_SKILLS_DIR, CLI_PACKAGE_ROOT } from '../core/paths.js';
/** Fallback directory for generated MCP stubs (when AICore/ files haven't been converted yet) */
const MCP_STUBS_DIR = join(CLI_PACKAGE_ROOT, '.aicore-mcp-stubs');
const MCP_STUBS_AGENTS_DIR = join(MCP_STUBS_DIR, 'agents');
const MCP_STUBS_SKILLS_DIR = join(MCP_STUBS_DIR, 'skills');
// ── Types ──
/** Supported stub schema versions */
const SUPPORTED_SCHEMAS = ['aicore-mcp-stub/v2', 'aicore-mcp-stub/v1'];
// ── Frontmatter Parsing ──
/** Parse YAML frontmatter and body from a markdown file */
export function parseMarkdownFrontmatter(content) {
    const match = content.match(/^---\r?\n([\s\S]*?)\r?\n---\r?\n?([\s\S]*)$/);
    if (!match)
        return null;
    const frontmatter = parseYaml(match[1] ?? '') ?? {};
    const body = match[2] ?? '';
    return { frontmatter, body };
}
// ── Stub Loading ──
/** Read and parse a single stub file */
export function parseStubFile(filePath) {
    if (!existsSync(filePath))
        return null;
    try {
        const raw = readFileSync(filePath, 'utf-8');
        const parsed = parseMarkdownFrontmatter(raw);
        if (!parsed)
            return null;
        const { frontmatter: fm } = parsed;
        const schema = fm.schema;
        // Validate schema
        if (!schema || !SUPPORTED_SCHEMAS.includes(schema)) {
            return null; // Not a stub file or unsupported version
        }
        const type = fm.type;
        if (type !== 'agent' && type !== 'skill')
            return null;
        const mcpObj = fm.mcp;
        let name = fm.name ??
            mcpObj?.params?.['name'] ??
            (typeof mcpObj?.params === 'object' && mcpObj.params !== null
                ? mcpObj.params.name
                : undefined);
        if (!name) {
            // Try to derive name from path
            const basename = filePath.split(/[/\\]/).pop()?.replace('.md', '');
            if (!basename)
                return null;
            name = basename;
        }
        return {
            path: filePath,
            schema,
            type: type,
            name: name,
            description: fm.description ?? '',
            mcp: fm.mcp ?? { server: 'codesquad', tool: `${type}.invoke`, params: { name: name } },
            requiresContext: fm.requires_context,
            input: fm.input,
            output: fm.output,
            requiredConfig: fm.required_config,
            mode: fm.mode,
            tags: fm.tags,
            userInvocable: (fm.user_invocable ?? fm.userInvocable),
        };
    }
    catch {
        return null;
    }
}
/** Find all agent stub files in AICore/agents/ (with fallback to .aicore-mcp-stubs/) */
export function loadAgentStubs() {
    // Primary: AICore/agents/ (expected after Phase 6 in-place conversion)
    if (existsSync(AICORE_AGENTS_DIR)) {
        const files = readdirSync(AICORE_AGENTS_DIR)
            .filter(f => extname(f) === '.md')
            .map(f => join(AICORE_AGENTS_DIR, f));
        const result = files
            .map(f => parseStubFile(f))
            .filter((s) => s !== null);
        if (result.length > 0)
            return result;
    }
    // Fallback: .aicore-mcp-stubs/agents/ (generated by `codesquad mcp convert-stubs`)
    if (existsSync(MCP_STUBS_AGENTS_DIR)) {
        const files = readdirSync(MCP_STUBS_AGENTS_DIR)
            .filter(f => extname(f) === '.md')
            .map(f => join(MCP_STUBS_AGENTS_DIR, f));
        return files
            .map(f => parseStubFile(f))
            .filter((s) => s !== null);
    }
    return [];
}
/** Find all skill stub files in AICore/skills/ (with fallback to .aicore-mcp-stubs/) */
export function loadSkillStubs() {
    // Primary: AICore/skills/ (expected after Phase 6 in-place conversion)
    if (existsSync(AICORE_SKILLS_DIR)) {
        const entries = readdirSync(AICORE_SKILLS_DIR, { withFileTypes: true })
            .filter(e => e.isDirectory())
            .map(e => {
            const skillPath = join(AICORE_SKILLS_DIR, e.name, 'SKILL.md');
            return existsSync(skillPath) ? skillPath : null;
        })
            .filter((p) => p !== null);
        const result = entries
            .map(f => parseStubFile(f))
            .filter((s) => s !== null);
        if (result.length > 0)
            return result;
    }
    // Fallback: .aicore-mcp-stubs/skills/ (generated by `codesquad mcp convert-stubs`)
    if (existsSync(MCP_STUBS_SKILLS_DIR)) {
        const entries = readdirSync(MCP_STUBS_SKILLS_DIR, { withFileTypes: true })
            .filter(e => e.isDirectory())
            .map(e => {
            const skillPath = join(MCP_STUBS_SKILLS_DIR, e.name, 'SKILL.md');
            return existsSync(skillPath) ? skillPath : null;
        })
            .filter((p) => p !== null);
        return entries
            .map(f => parseStubFile(f))
            .filter((s) => s !== null);
    }
    return [];
}
/** Load all stubs (agents + skills) */
export function loadAllStubs() {
    return {
        agents: loadAgentStubs(),
        skills: loadSkillStubs(),
    };
}
/** Find a specific agent stub by name (checks AICore/ first, then .aicore-mcp-stubs/) */
export function findAgentStub(name) {
    // Primary: AICore/agents/
    let filePath = join(AICORE_AGENTS_DIR, `${name}.md`);
    if (existsSync(filePath)) {
        const stub = parseStubFile(filePath);
        if (stub)
            return stub;
    }
    // Fallback: .aicore-mcp-stubs/agents/
    filePath = join(MCP_STUBS_AGENTS_DIR, `${name}.md`);
    if (existsSync(filePath)) {
        const stub = parseStubFile(filePath);
        return stub ?? undefined;
    }
    return undefined;
}
/** Find a specific skill stub by name (checks AICore/ first, then .aicore-mcp-stubs/) */
export function findSkillStub(name) {
    // Primary: AICore/skills/
    let filePath = join(AICORE_SKILLS_DIR, name, 'SKILL.md');
    if (existsSync(filePath)) {
        const stub = parseStubFile(filePath);
        if (stub)
            return stub;
    }
    // Fallback: .aicore-mcp-stubs/skills/
    filePath = join(MCP_STUBS_SKILLS_DIR, name, 'SKILL.md');
    if (existsSync(filePath)) {
        const stub = parseStubFile(filePath);
        return stub ?? undefined;
    }
    return undefined;
}
/** Filter stubs by tag */
export function filterByTag(stubs, tag) {
    return stubs.filter(s => s.tags?.includes(tag));
}
/** Search stubs by keyword in name and description */
export function searchStubs(stubs, query) {
    const lower = query.toLowerCase();
    return stubs.filter(s => s.name.toLowerCase().includes(lower) ||
        s.description.toLowerCase().includes(lower) ||
        s.tags?.some(t => t.toLowerCase().includes(lower)));
}
//# sourceMappingURL=stub-loader.js.map