/**
 * Template Copier
 *
 * Copies template files from the CLI package's docs/ directory
 * into a project's docs/ directory. Used by `codesquad start`.
 * (init uses installProjectFiles via Config/project_file_install_config.yaml)
 */
import { existsSync, mkdirSync, readFileSync, writeFileSync, readdirSync, statSync } from 'fs';
import { join, dirname, relative, resolve } from 'path';
import { fileURLToPath } from 'url';
import chalk from 'chalk';
import { logger } from '../utils/logger.js';
const __filename = fileURLToPath(import.meta.url);
const __dirname = dirname(__filename);
const CLI_PACKAGE_ROOT = resolve(__dirname, '..', '..');
/** Source template directory within the CLI package — uses canonical docs/ */
const TEMPLATES_SOURCE = join(CLI_PACKAGE_ROOT, 'docs');
/** Files/directories that should NOT be copied (engine-reference is generated by setup-engine) */
const EXCLUDED_DIRS = new Set(['engine-reference']);
/**
 * Copy template docs directory to the target project.
 * Skips files that already exist in the target (unless force is true).
 */
export function copyTemplates(targetPath, force = false) {
    const result = { copied: 0, skipped: 0, files: [] };
    const targetDocsDir = join(targetPath, 'docs');
    if (!existsSync(TEMPLATES_SOURCE)) {
        logger.warn(`Template directory not found: ${TEMPLATES_SOURCE}`);
        return result;
    }
    // Ensure target docs directory exists
    mkdirSync(targetDocsDir, { recursive: true });
    // Walk and copy
    walkAndCopy(TEMPLATES_SOURCE, targetDocsDir, result, force);
    return result;
}
/** Recursively walk source directory and copy files */
function walkAndCopy(srcDir, destDir, result, force) {
    const entries = readdirSync(srcDir);
    for (const entry of entries) {
        const srcPath = join(srcDir, entry);
        const destPath = join(destDir, entry);
        const stat = statSync(srcPath);
        if (stat.isDirectory()) {
            // Skip excluded directories
            if (EXCLUDED_DIRS.has(entry))
                continue;
            // Ensure destination directory exists
            mkdirSync(destPath, { recursive: true });
            // Recurse into subdirectory
            walkAndCopy(srcPath, destPath, result, force);
        }
        else {
            // Copy file
            if (existsSync(destPath) && !force) {
                result.skipped++;
                result.files.push({
                    source: relative(CLI_PACKAGE_ROOT, srcPath),
                    dest: entry,
                    status: 'skipped',
                });
            }
            else {
                try {
                    const content = readFileSync(srcPath);
                    writeFileSync(destPath, content);
                    result.copied++;
                    result.files.push({
                        source: relative(CLI_PACKAGE_ROOT, srcPath),
                        dest: relative(destDir, destPath),
                        status: 'copied',
                    });
                }
                catch (err) {
                    result.files.push({
                        source: relative(CLI_PACKAGE_ROOT, srcPath),
                        dest: relative(destDir, destPath),
                        status: 'error',
                        error: String(err),
                    });
                }
            }
        }
    }
}
/** Print a summary of the copy operation */
export function printCopySummary(result) {
    if (result.copied === 0 && result.skipped === 0) {
        logger.info('No templates to copy.');
        return;
    }
    logger.success(`Templates: ${result.copied} copied, ${result.skipped} skipped (already exist)`);
    if (result.copied > 0) {
        console.log(chalk.dim('  Copied files:'));
        for (const f of result.files.filter((f) => f.status === 'copied')) {
            console.log(chalk.dim(`    → ${f.dest}`));
        }
    }
    const errors = result.files.filter((f) => f.status === 'error');
    if (errors.length > 0) {
        for (const e of errors) {
            logger.error(`Failed to copy ${e.source}: ${e.error}`);
        }
    }
}
//# sourceMappingURL=template-copier.js.map