

version: 1

project_file_install_config:
  root_system_file: 
    from: Root/CODESQUAD.md
    dist: ${Project}/CODESQUAD.md
  design_dir:
    from: Root/design
    dist: ${Project}/design
  codesquad_system_file: 
    from: Root/.codesquad/CODESQUAD.md
    dist: ${Project}/.codesquad/CODESQUAD.md
  codesquad_settings_file: 
    from: Root/.codesquad/settings.json
    dist: ${Project}/.codesquad/settings.json
  codesquad_statusline_file: 
    from: Root/.codesquad/statusline.sh
    dist: ${Project}/.codesquad/statusline.sh
  root_docs_dir:
    from: Root/docs
    dist: ${Project}/docs

